esphome:
  name: esp32-stick

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: "generate api key"

ota:
#  password: "generate ota password"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1

#  manual_ip:
#    static_ip: 10.0.0.42
#    gateway: 10.0.0.1
#    subnet: 255.255.255.0

light:
  - platform: status_led
    name: "Switch state"
    pin: GPIO2
binary_sensor:
  - platform: gpio
    pin:
      number: 12
      mode:
        input: true
        pullup: true
    name: "vypínač"